In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
#pip install xgboost

In [2]:
train = pd.read_csv("train.csv")
print(train.shape)
train.head()

(3533, 48)

,ID,G1,G2,G3,G4,G5,T1,T2,T3,T4,...,R3,R4,R5,R6,R7,O1,O2,O3,O4,Y
0,1,0,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
1,2,0,1,0,1,0,1,1,0,0,...,0,0,0,1,0,0,0,1,0,1
2,3,1,1,0,1,1,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
3,4,1,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,1
4,5,0,0,1,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1

In [3]:
test = pd.read_csv("test.csv")
print(test.shape)
test.head()

(300, 47)

,ID,G1,G2,G3,G4,G5,T1,T2,T3,T4,...,R2,R3,R4,R5,R6,R7,O1,O2,O3,O4
0,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,3,1,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,4,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,5,1,0,1,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [4]:
def convert(x):
    ids = np.unique(x)
    vals = 0
    pd = np.zeros((x.shape))
    for item in ids:
        pd[x==item] = vals
    return pd
X = train.drop(['Y'],axis=1)
X['ID'] = convert(X['ID'].values)

test['ID'] = convert(test['ID'].values)

X = X.apply(pd.to_numeric, errors='coerce')
X.fillna(0, inplace = True)

test = test.apply(pd.to_numeric, errors='coerce')
test.fillna(0, inplace = True)

y = train['Y']

X = X.astype(float)
test = test.astype(float)
pd.options.display.max_columns = None
X.head()

,ID,G1,G2,G3,G4,G5,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28,T29,T30,R1,R2,R3,R4,R5,R6,R7,O1,O2,O3,O4
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20,random_state=0)
y_test

202     1
1643    1
569     1
2000    3
2600    3
       ..
2420    3
999     1
3056    3
154     1
2240    3
Name: Y, Length: 707, dtype: int64

In [6]:
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn import metrics
from  sklearn.datasets  import  make_hastie_10_2
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from xgboost import plot_importance
from sklearn import metrics
clf = GradientBoostingClassifier(loss="deviance", learning_rate=0.1, n_estimators=150)
#clf=  XGBClassifier(n_estimators=600,learning_rate= 0.1)
clf.fit(X_train, y_train)
y_pred = clf.predict(test)
y_pred
results = np.around(clf.predict_proba(test),2)
results.transpose()

array([[0.36, 0.01, 0.48, 0.65, 0.01, 0.45, 0.01, 0.01, 0.64, 0.62, 0.35,
        0.56, 0.  , 0.47, 0.07, 0.53, 0.64, 0.07, 0.42, 0.47, 0.01, 0.94,
        0.09, 0.01, 0.54, 0.01, 0.  , 0.01, 0.  , 0.01, 0.29, 0.01, 0.56,
        0.5 , 0.47, 0.03, 0.47, 0.49, 0.02, 0.01, 0.47, 0.03, 0.01, 0.  ,
        0.47, 0.39, 0.44, 0.49, 0.01, 0.48, 0.47, 0.02, 0.97, 0.96, 0.01,
        0.49, 0.49, 0.02, 0.65, 0.44, 0.01, 0.62, 0.39, 0.4 , 0.42, 0.  ,
        0.01, 0.44, 0.45, 0.94, 0.38, 0.01, 0.03, 0.01, 0.5 , 0.47, 0.01,
        0.01, 0.56, 0.45, 0.01, 0.41, 0.47, 0.15, 0.03, 0.44, 0.47, 0.84,
        0.4 , 0.47, 0.01, 0.54, 0.56, 0.01, 0.45, 0.01, 0.01, 0.56, 0.67,
        0.47, 0.01, 0.  , 0.01, 0.  , 0.82, 0.45, 0.5 , 0.47, 0.45, 0.11,
        0.64, 0.54, 0.49, 0.01, 0.03, 0.48, 0.5 , 0.44, 0.47, 0.01, 0.49,
        0.47, 0.49, 0.39, 0.48, 0.03, 0.49, 0.42, 0.49, 0.  , 0.32, 0.  ,
        0.  , 0.  , 0.01, 0.48, 0.01, 0.77, 0.43, 0.11, 0.63, 0.47, 0.67,
        0.47, 0.47, 0.47, 0.01, 0.56, 0.11, 0.5 , 0.01, 0.5 , 0.54, 0.5 ,
        0.48, 0.84, 0.44, 0.97, 0.  , 0.01, 0.01, 0.  , 0.42, 0.47, 0.62,
        0.57, 0.01, 0.  , 0.49, 0.01, 0.86, 0.5 , 0.02, 0.11, 0.75, 0.74,
        0.47, 0.54, 0.01, 0.49, 0.01, 0.4 , 0.47, 0.49, 0.5 , 0.01, 0.41,
        0.55, 0.74, 0.01, 0.01, 0.01, 0.67, 0.47, 0.47, 0.01, 0.67, 0.07,
        0.43, 0.5 , 0.26, 0.01, 0.01, 0.47, 0.01, 0.45, 0.23, 0.46, 0.45,
        0.44, 0.68, 0.01, 0.49, 0.45, 0.5 , 0.47, 0.03, 0.42, 0.  , 0.03,
        0.44, 0.22, 0.  , 0.96, 0.47, 0.  , 0.45, 0.01, 0.47, 0.47, 0.02,
        0.07, 0.48, 0.46, 0.47, 0.47, 0.49, 0.64, 0.49, 0.52, 0.54, 0.52,
        0.01, 0.5 , 0.43, 0.01, 0.52, 0.44, 0.68, 0.44, 0.01, 0.42, 0.5 ,
        0.48, 0.47, 0.48, 0.  , 0.5 , 0.03, 0.01, 0.31, 0.43, 0.56, 0.45,
        0.6 , 0.42, 0.53, 0.  , 0.44, 0.6 , 0.98, 0.54, 0.5 , 0.55, 0.47,
        0.  , 0.37, 0.39, 0.45, 0.01, 0.01, 0.05, 0.47, 0.53, 0.94, 0.12,
        0.39, 0.46, 0.64, 0.75, 0.45, 0.  , 0.11, 0.99, 0.55, 0.62, 0.47,
        0.68, 0.02, 0.5 ],
       [0.  , 0.98, 0.  , 0.  , 0.98, 0.  , 0.98, 0.98, 0.  , 0.  , 0.  ,
        0.  , 1.  , 0.  , 0.86, 0.  , 0.  , 0.86, 0.04, 0.  , 0.98, 0.  ,
        0.71, 0.98, 0.  , 0.98, 1.  , 0.98, 1.  , 0.98, 0.  , 0.98, 0.  ,
        0.  , 0.  , 0.94, 0.  , 0.  , 0.98, 0.98, 0.  , 0.  , 0.98, 1.  ,
        0.  , 0.  , 0.  , 0.  , 0.98, 0.  , 0.  , 0.96, 0.  , 0.  , 0.98,
        0.  , 0.  , 0.96, 0.  , 0.  , 0.98, 0.  , 0.  , 0.  , 0.  , 1.  ,
        0.98, 0.  , 0.  , 0.  , 0.  , 0.98, 0.94, 0.98, 0.  , 0.  , 0.98,
        0.98, 0.  , 0.  , 0.98, 0.  , 0.  , 0.  , 0.95, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.98, 0.  , 0.  , 0.98, 0.  , 0.98, 0.97, 0.  , 0.  ,
        0.  , 0.98, 1.  , 0.98, 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.76,
        0.  , 0.  , 0.  , 0.98, 0.  , 0.  , 0.  , 0.  , 0.04, 0.98, 0.  ,
        0.04, 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.  , 0.99, 0.  , 1.  ,
        1.  , 1.  , 0.98, 0.  , 0.95, 0.  , 0.  , 0.76, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.98, 0.  , 0.76, 0.  , 0.98, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.99, 0.98, 0.98, 0.99, 0.  , 0.  , 0.  ,
        0.  , 0.98, 0.99, 0.  , 0.98, 0.  , 0.  , 0.95, 0.76, 0.  , 0.  ,
        0.04, 0.  , 0.98, 0.  , 0.98, 0.  , 0.  , 0.  , 0.  , 0.98, 0.  ,
        0.  , 0.  , 0.98, 0.98, 0.98, 0.  , 0.  , 0.  , 0.98, 0.  , 0.86,
        0.07, 0.  , 0.  , 0.98, 0.98, 0.  , 0.98, 0.  , 0.43, 0.  , 0.  ,
        0.  , 0.  , 0.98, 0.  , 0.  , 0.  , 0.  , 0.94, 0.  , 0.99, 0.95,
        0.  , 0.  , 0.99, 0.  , 0.  , 1.  , 0.  , 0.98, 0.  , 0.  , 0.  ,
        0.86, 0.  , 0.04, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.98, 0.  , 0.07, 0.98, 0.  , 0.  , 0.  , 0.  , 0.98, 0.04, 0.  ,
        0.  , 0.  , 0.  , 1.  , 0.  , 0.95, 0.98, 0.  , 0.07, 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.99, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        1.  , 0.1 , 0.  , 0.  , 0.97, 0.98, 0.86, 0.  , 0.  , 0.  , 0.03,
        0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.76, 0.  , 0.  , 0.  , 0.04,
        0.  , 0.98, 0.  ],
       [0.64, 0.01, 0.52, 0.35, 0.02, 0.55, 0.01, 0.01, 0.36, 0.38, 0.65,
        0.44, 0.  , 0.53, 0.07, 0.47, 0.36, 0.07, 0.54, 0.53, 0.01, 0.06,
        0.2 , 0.01, 0.46, 0.01, 0.  , 0.01, 0.  , 0.01, 0.71, 0.01, 0.44,
        0.5 , 0.53, 0.03, 0.53, 0.51, 0.01, 0.01, 0.53, 0.97, 0.01, 0.  ,
        0.53, 0.61, 0.56, 0.51, 0.01, 0.52, 0.53, 0.02, 0.03, 0.04, 0.01,
        0.51, 0.51, 0.02, 0.35, 0.56, 0.01, 0.38, 0.61, 0.6 , 0.57, 0.  ,
        0.01, 0.56, 0.55, 0.06, 0.62, 0.01, 0.02, 0.01, 0.5 , 0.53, 0.01,
        0.01, 0.44, 0.55, 0.01, 0.59, 0.53, 0.85, 0.02, 0.56, 0.53, 0.16,
        0.6 , 0.53, 0.01, 0.46, 0.44, 0.01, 0.55, 0.01, 0.02, 0.44, 0.33,
        0.53, 0.01, 0.  , 0.01, 0.  , 0.18, 0.55, 0.5 , 0.53, 0.55, 0.13,
        0.36, 0.46, 0.51, 0.01, 0.96, 0.52, 0.5 , 0.56, 0.49, 0.01, 0.51,
        0.49, 0.51, 0.61, 0.52, 0.97, 0.51, 0.54, 0.51, 0.  , 0.68, 0.  ,
        0.  , 0.  , 0.01, 0.52, 0.04, 0.23, 0.57, 0.13, 0.37, 0.53, 0.33,
        0.53, 0.53, 0.53, 0.01, 0.44, 0.13, 0.5 , 0.01, 0.5 , 0.46, 0.5 ,
        0.52, 0.16, 0.56, 0.03, 0.  , 0.01, 0.01, 0.  , 0.58, 0.53, 0.38,
        0.43, 0.01, 0.01, 0.51, 0.01, 0.14, 0.5 , 0.03, 0.13, 0.25, 0.26,
        0.49, 0.46, 0.01, 0.51, 0.01, 0.6 , 0.53, 0.51, 0.5 , 0.01, 0.59,
        0.45, 0.26, 0.01, 0.01, 0.01, 0.33, 0.53, 0.53, 0.01, 0.33, 0.07,
        0.51, 0.5 , 0.74, 0.01, 0.01, 0.53, 0.01, 0.55, 0.35, 0.54, 0.55,
        0.56, 0.31, 0.01, 0.51, 0.55, 0.5 , 0.53, 0.02, 0.58, 0.01, 0.03,
        0.56, 0.78, 0.  , 0.04, 0.53, 0.  , 0.55, 0.01, 0.53, 0.53, 0.98,
        0.07, 0.52, 0.5 , 0.53, 0.53, 0.51, 0.36, 0.51, 0.48, 0.46, 0.48,
        0.01, 0.5 , 0.51, 0.01, 0.48, 0.56, 0.32, 0.56, 0.01, 0.54, 0.5 ,
        0.52, 0.53, 0.52, 0.  , 0.5 , 0.03, 0.01, 0.69, 0.51, 0.44, 0.55,
        0.4 , 0.58, 0.47, 0.  , 0.56, 0.4 , 0.02, 0.46, 0.5 , 0.45, 0.53,
        0.  , 0.53, 0.61, 0.55, 0.02, 0.01, 0.09, 0.53, 0.47, 0.06, 0.85,
        0.61, 0.54, 0.36, 0.25, 0.55, 0.  , 0.13, 0.01, 0.45, 0.38, 0.49,
        0.31, 0.01, 0.5 ]])

In [7]:
res = pd.DataFrame(results, columns = ['C1','C2','C3'])
df = pd.DataFrame(data=res)
df.to_csv('g.csv')

In [8]:
XGBClassifier(n_estimators=15cc0,
        # 如同學習率
        learning_rate= 0.3, 
        # 構建樹的深度，越大越容易過擬合    
        max_depth=6, 
        # 隨機取樣訓練樣本 訓練例項的子取樣比
        subsample=1, 
        # 用於控制是否後剪枝的引數,越大越保守，一般0.1、0.2這樣子
        gamma=0, 
        # 控制模型複雜度的權重值的L2正則化項引數，引數越大，模型越不容易過擬合。
        reg_lambda=1,  
        
        #最大增量步長，我們允許每個樹的權重估計。
        max_delta_step=0,
        # 生成樹時進行的列取樣 
        colsample_bytree=1, 

        # 這個引數預設是 1，是每個葉子裡面 h 的和至少是多少，對正負樣本不均衡時的 0-1 分類而言
        # 假設 h 在 0.01 附近，min_child_weight 為 1 意味著葉子節點中最少需要包含 100 個樣本。
        #這個引數非常影響結果，控制葉子節點中二階導的和的最小值，該引數值越小，越容易 overfitting。
        min_child_weight=1, 

        #隨機種子
        seed=1000 )

SyntaxError: invalid syntax (<ipython-input-8-212977b1b850>, line 1)